### ISSUE TITLE
How do I call `tell` but not end the session?

### ISSUE THREAD

**Issue by trevorwang** [jovotech/jovo-framework-nodejs#101]
Right now I have to use `ask` to keep the session.
But it looks strange that the bot tell something to user but use a `ask` method

**Comment by jankoenig** [comment]
You have to use the `ask` method of you're expecting a response from a user. What type of interaction at you looking for?

**Comment by trevorwang** [comment]
My application has 4 functions.  When I switch to my application from google assistant, one of the function will be automatically started. After things are done, give user some feedback.
But I want not to end the session. I still want to start any of others function by some command. Instead of talk to google assistant to start my application again.

**Comment by jankoenig** [comment]
Then `ask` is the way to go

**Comment by trevorwang** [comment]
Got it. Thanks.
