### ISSUE TITLE
Error updating the skill interaction model

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-framework-nodejs#105]
Hello, 

Thanks a lot (again) for providing the Jovo framework!

I have an issue deploying the interaction model to the Alexa console with the Jovo CLI.

Here is my model file fr-FR.json . (it's the example one for now). 

```{
    "invocation":"my test app",
    "intents":[
        {
            "name":"HelloWorldIntent",
            "phrases":[
                "hello",
                "say hello",
                "say hello world"
            ]
        },
        {
            "name":"MyNameIsIntent",
            "phrases":[
                "{name}",
                "my name is {name}",
                "i am {name}",
                "you can call me {name}"
            ],
            "inputs":[
                {
                    "name":"name",
                    "type":{
                        "alexa":"AMAZON.US_FIRST_NAME",
                        "dialogflow":"@sys.given-name"
                    }
                }
            ]
        }
    ]
}
```

I do  `jovo build` then `jovo deploy`

And the Alexa console is not updated. Here are the logs : 

```   ✔ Deploying Alexa Skill
     ✔ Updating Alexa Skill project for ASK profile default
       Skill Name: redacted (fr-FR)
       Skill ID: amzn1.ask.skill.99c3818c-f294-4be3-8fb1-XXX
       Invocation Name: my test app (fr-FR)
       Endpoint: https://webhook.jovo.cloud/abee97d9-7413-49f1-87fb-XXX
     ✔ Deploying Interaction Model, waiting for build
       ✔ fr-FR
   ✔ Deploying Google Action
     ✔ Creating file /googleAction/dialogflow_agent.zip
       Language model: fr-FR
       Fulfillment Endpoint: https://webhook.jovo.cloud/abee97d9-7413-49f1-87fb-XXX

  Deployment completed.

Unhandled Rejection at: Promise Promise { <rejected> undefined } reason: undefined
```

I tried removing the platforms folder and redo `jovo build` then `jovo run`
Here is what I get : 
```   ❯ Deploying Alexa Skill
     ✖ Creating Alexa Skill project for ASK profile default
       -> Unexpected end of JSON input
       Deploying Interaction Model, waiting for build
     Deploying Google Action

Unexpected end of JSON input
```

Thanks for your help.

**Comment by aswetlow** [comment]
Hey @QuentinDela!
Please post your skill.json from your /platforms/alexaSkill/ folder.

**Comment by QuentinDela** [comment]
```
{
	"manifest": {
		"publishingInformation": {
			"locales": {
				"fr-FR": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"name": "redacted",
					"description": "Sample Full Description"
				}
			},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": "https://webhook.jovo.cloud/abee97d9-7413-49f1-87fb-b9c0485d13f2"
				}
			}
		},
		"manifestVersion": "1.0"
	}
}
```

**Comment by aswetlow** [comment]
AMAZON.US_FIRST_NAME is not supported in fr-FR. AMAZON.FirstName should work.

**Comment by QuentinDela** [comment]
It's working, thanks for the follow up.

**Comment by shambhavii** [comment]
Hello 
I have an issue in jovo Deploying Interaction Model even though i changed AZON.US_FIRST_NAME is  fr-FR. AMAZON.FirstName it is show same error.can u please help me out.
❯ Deploying Alexa Skill  
✖ Creating Alexa Skill project for ASK profile default
       -> Unexpected end of JSON input
       Deploying Interaction Model, waiting for build

Unexpected end of JSON input

**Comment by jankoenig** [comment]
Hi @shambhavii, have you done `jovo build` again before trying to deploy it?
What does your `fr-FR.json` look like in the `platforms/alexaSkill/models` folder?

**Comment by shambhavii** [comment]
yes i have done the jovo build before deploy. In platforms/alexaSkill/models looks like
                                                          "name": "name",
							"type": "AMAZON.US_FIRST_NAME"

**Comment by jankoenig** [comment]
Hmm, so you changed it in your `models` folder to `AMAZON.FirstName` , then did `$ jovo build` and  it was still `AMAZON.US_FIRST_NAME ` in `platforms/alexaSkill/models`? Are you sure you did all the steps in the right order? The `models` content overrides the alexaSkill content with jovo build

**Comment by shambhavii** [comment]
ya i got it now i have changed the models and done in right order. Thank you so much .
