### ISSUE TITLE
Chatbase Analytics

### ISSUE THREAD

**Issue by JayakumarManian** [jovotech/jovo-framework-nodejs#109]
Chatbase class map missing .
app.addChatbaseAnalytics('4ab9ef9c-8dba-4812-9bad-931addaa0494', '1.2');

\jovo-framework\lib\integrations\analytics\analytics.js:65
this.services[name] = new classesMapping[name](serviceConfig);

**Comment by jankoenig** [comment]
Hey @JayakumarManian, are you sure you're working with `jovo-framework v1.1`

**Comment by JayakumarManian** [comment]
Yes @jankoenig latest version only . Jovo CLI Version: 1.0.10 & Updated npm jovo-framework.

**Comment by JayakumarManian** [comment]
@jankoenig 'KaanKC ' chatbase integration code not merged properly.

**Comment by JayakumarManian** [comment]
Check & confirm repository : https://github.com/jovotech/jovo-framework-nodejs/tree/master/lib/integrations/analytics
Pls do required changes ASAP.

**Comment by KaanKC** [comment]
@JayakumarManian I am very sorry for the inconvenience. We are doing our best to fix the issue.

**Comment by KaanKC** [comment]
@JayakumarManian The issue should be fixed now.

**Comment by JayakumarManian** [comment]
👍
