### ISSUE TITLE
Inputs in DialogFlowV2 requests are plain strings (not objects)

### ISSUE THREAD

**Issue by fgnass** [jovotech/jovo-framework-nodejs#116]
I uploaded the sample action to Dialogflow. After switching to the V2 API the handler functions no longer receive objects as arguments but plain strings:

```js
{
  'MyNameIsIntent': function(name) {
    this.tell('Hello ' + name.value); // <-- name is a string, not an object!
  }
}
```

My guess is that the code in [dialogFlowV2Request.js:39](https://github.com/jovotech/jovo-framework-nodejs/blob/master/lib/platforms/googleaction/request/dialogFlowV2Request.js#L39) should do something similar as in the V1 implementation and create an object with `name`, `value` and `key` properties.

As I'm completely new to Jovo, I might be missing something obvious here. If not and you can confirm that this is a bug I could create a PR with a fix.

**Comment by jankoenig** [comment]
Thanks a lot! Would really appreciate a PR :)
