### ISSUE TITLE
A previousOutput object

### ISSUE THREAD

**Issue by bcnichols3** [jovotech/jovo-framework-nodejs#121]
I prefer to keep what I call a prev object on my session, which holds onto the previous output speech, reprompt and state. I use this in several places, which seem to come up in just about every bot I make:

- AMAZON.RepeatIntent: User request for the bot to repeat itself, and I can more easily do that if I have reference to what my bot has just said
- Unhandled flow: apologize for not understanding the user, then repeat the most recent reprompt (very useful if the reprompts are written intelligently)
- Referencing where the user had just been from inside another state, and alter the speech accordingly -- improving the illusion of conversationality

It would be great if Jovo had this kind of functionality built in. The onResponse function is a great place to build this, but copy-pasting code every time into a new project is tedious.

**Comment by jankoenig** [comment]
Thanks @bcnichols3, this looks like a perfect addition to our User class, which already stores metadata: https://www.jovo.tech/framework/docs/data/user

**Comment by jankoenig** [comment]
Hi @bcnichols3, we're on it. Would you mind sharing how exactly you're saving it in the `onResponse` function? Are you saving `speech`, `reprompt` and `state` as strings and that's it or are you doing anything else?

**Comment by jankoenig** [comment]
Hi @bcnichols3,

@KaanKC is currently working on this. You can take a look at the changes in this PR:  #138 
We settled on calling it user context. E.g. you can access the previous intent with `this.user().context.prev[0].request.intent`

**Comment by bcnichols3** [comment]
This looks awesome @jankoenig. Are the `speech` and `reprompt` plaintext or SSML markup? I had been saving plain text, so it's easily appended to a new `ask` or `tell`.

Also great to have the user request; I don't require that on any of my current projects but I can imagine somebody has a use case for that.

**Comment by KaanKC** [comment]
It's plain text 👍

**Comment by bcnichols3** [comment]
Awesome @KaanKC! Does this have a release date yet?

**Comment by KaanKC** [comment]
We're planning to release the feature with version 1.2, which we hope to publish by the end of the week. 🤞

**Comment by jankoenig** [comment]
Thanks a lot @bcnichols3, this feature was added by @KaanKC  to the `v1.2` release. Take a look at the announcement here: https://www.jovo.tech/blog/jovo-framework-v1-2/

**Comment by bcnichols3** [comment]
I've been playing around with it since lunch, Jan! Just from today I'm using this for repeat, unhandled, custom analytics, contextual goodbyes and even dev logging. Great work! I got to delete a lot of code thanks to this new API.

**Comment by jankoenig** [comment]
Haha awesome!
Btw did you know that we even added `this.repeat()`?
 
https://www.jovo.tech/framework/docs/output#repeat
