### ISSUE TITLE
Some questions about going to global state

### ISSUE THREAD

**Issue by tony-gutierrez** [jovotech/jovo-framework-nodejs#127]
In alexa I used to do this:

`this.handler.state = '';`

 In Jovo for now I am doing: `this.toStatelessIntent('null');`, and created a 'null' intent.

Is there a better way? Also how would I do a tell and go back to global? 
`this.followUpState('').tell('blah blah');`

**Comment by jankoenig** [comment]
You can do `this.removeState()` or `this.followUpState(null)`

**Comment by jankoenig** [comment]
Just added it to the docs as well: https://github.com/jovotech/jovo-framework-nodejs/tree/master/docs/04_app-logic/01_routing#remove-a-state

Please reopen if this doesn't solve your problem.
