### ISSUE TITLE
TypeError: _.get(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by tony-gutierrez** [jovotech/jovo-framework-nodejs#129]
```
TypeError: _.get(...) is not a function or its return value is not iterable
    at GoogleActionRequest.getSignInStatus (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/platforms/googleaction/request/googleActionRequest.js:167:32)
```
suggest maybe adding a default value:
```
for (let argument of _.get(this, 'inputs[0]["arguments"]', [])) {
```

**Comment by jankoenig** [comment]
Thanks @tony-gutierrez , where are you debugging, in Dialogflow or the Actions on Google Simulator?

**Comment by tony-gutierrez** [comment]
At the moment, actions simulator. 

I realize some of these may not occur in real world scenarios but they interrupt development. Im going to keep noting them, just close if you're not interested.

**Comment by jankoenig** [comment]
Thanks, keep them coming! Really helpful to see where users are running into problems

**Comment by aswetlow** [comment]
Sorry, it got lost somehow. I added your suggestion. It will be published with the next version. Thanks @tony-gutierrez
