### ISSUE TITLE
Firebase Cloud Function Server Config

### ISSUE THREAD

**Issue by gnomeontherun** [jovotech/jovo-framework-nodejs#139]
It would be most excellent to support Firebase Cloud Functions, in case you wish to go full in on the Google platform.

**Comment by gnomeontherun** [comment]
I'm just crazy, this is there but was not evident at first.

**Comment by eviathan** [comment]
HI there,

Can you link me to what you found please?

**Comment by ttretau** [comment]
Managed it to work on cloud functions with: 
`functions.https.onRequest((request, response) => {
    app.handleWebhook(request, response);
});`
And you need to disable persistence in config: `saveUserOnResponseEnabled: false`
