### ISSUE TITLE
Chatbase integration — track agent

### ISSUE THREAD

**Issue by bcnichols3** [jovotech/jovo-framework-nodejs#140]
I'm noticing your Chatbase integration doesn't leverage all of what Chatbase can do. It's really only recording enough data to use the Session Flow chart, and even then it's not recording user slots. It's also not providing an easy way to post Chatbase events — which is probably fine for now since funneling by events isn't even available yet on the platform — but not being able to properly use Chatbase Messages is a bummer. It's super helpful for non-technical teammates who want to spool through user interactions.

Is there an easy way to add Chatbase agent messages to Jovo's analytics flow? Perhaps by using the new `context` api you're working on? 😉 😉

**Comment by jankoenig** [comment]
Hey @bcnichols3, thanks for the suggestion. We'll look into it
