### ISSUE TITLE
this.nlu error with Google Assistant Requests

### ISSUE THREAD

**Issue by chrisaspringer** [jovotech/jovo-framework-nodejs#142]
I got this error: 
```
TypeError: this.nlu.getIntentName is not a function
    at GoogleAction.getIntentName (/var/task/node_modules/jovo-framework/lib/platforms/googleaction/googleAction.js:66:25)
    at Jovo.getIntentName (/var/task/node_modules/jovo-framework/lib/jovo.js:289:57)
    at Promise (/var/task/node_modules/jovo-framework/lib/routing.js:54:50)
    at new Promise (<anonymous>)
    at Routing.route (/var/task/node_modules/jovo-framework/lib/routing.js:24:16)
    at loadUserDataOnRequest.then.then.then.then (/var/task/node_modules/jovo-framework/lib/jovo.js:174:38)
    at <anonymous>
```

...when testing my function with a Google Assistant Request. I think the format of the requests from Google Assistant must have changed because my old test worked. I am using the Dialogflow v2 API, but have for the life of this particular project, so that hasn't changed.

On the Google Assistant Simulator side, the logs say `MalformedResponse: 'final_response' must be set` because the app logic is returning `null`.

**Comment by aswetlow** [comment]
Hey @chrisaspringer. Could you post the relevant parts of your handler? Thanks

**Comment by chrisaspringer** [comment]
`'use strict';

const { App } = require('jovo-framework');
const contentfulService = require('./contentful-service');
const helpers = require('./helpers')
const { getContentfulData } = contentfulService;
const { getMaskedIntents, getIntentMessages } = helpers;

const config = {
  logging: true
};

const app = new App(config);

app.setHandler({
  LAUNCH: function () {
    this.toIntent('WelcomeIntent');
  },

  // basically the launch intent
  WelcomeIntent: async function () {
    //if (!this.getSessionAttribute('intentData')) {
    // get the contentful data first
    // param true => live data
    // param false => local json for testing
    const rawIntentData = await getContentfulData(false);
    if (rawIntentData) {
      // process the response down
      const intentData = getMaskedIntents(rawIntentData);
      this.setSessionAttribute('intentData', JSON.stringify(intentData.items));
    }
    //}

    // parsing messages data from the fetch above
    let messages = getIntentMessages('WelcomeIntent', this.getSessionAttribute('intentData'));

    let speech = messages[0].fields.copy;
    let reprompt = 'Please answer with a yes or no.';
    this.followUpState('WelcomeState').ask(speech, reprompt);
  },

  // current topics
  CurrentTopicsIntent: function () {
    let messages = getIntentMessages('CurrentTopicsIntent', this.getSessionAttribute('intentData'));

    let speech = messages[0].fields.copy;
    this.ask(speech);
  },


  // state handling of generic intents
  WelcomeState: {
    YesIntent: function () {
      this.toIntent('CurrentTopicsIntent');
    },
    NoIntent: function () {
      let speech = 'Well, that is all I can offer, so have a good day.';
      this.tell(speech);
    }
  }
});

module.exports.app = app;
`

**Comment by chrisaspringer** [comment]
This handler is hosting on AWS Lambda running Node 8.10. It's used for both the Alexa Skill and Google Action fulfillment. I do have some async logic going on, but it works just fine for Alexa...

**Comment by chrisaspringer** [comment]
I'm wondering if it has to do with returning a promise, based on this issue. I'll look into it. https://github.com/actions-on-google/actions-on-google-nodejs/issues/117

**Comment by chrisaspringer** [comment]
I'm getting pretty desperate. Any help would be appreciated, even if some info on what would cause `this.nlu.getIntentName is not a function` error in the first place.

**Comment by aswetlow** [comment]
I have never used async/await within Jovo yet. Let me check.

**Comment by aswetlow** [comment]
I don't think it's an issue with async/await. Could you post the request json? (the full request object, not the one from the simulator/request tab) Thanks.

**Comment by chrisaspringer** [comment]
This was what was logged as the request in the Google Cloud logs. If there's another log I should be looking at for the request please let me know. Thanks again.
```{
  "user": {
    "userId": "xxxxx",
    "locale": "en-US",
    "lastSeen": "2018-05-14T21:39:38Z"
  },
  "conversation": {
    "conversationId": "xxxxxx",
    "type": "NEW"
  },
  "inputs": [
    {
      "intent": "actions.intent.MAIN",
      "rawInputs": [
        {
          "inputType": "VOICE",
          "query": "talk to my test app"
        }
      ]
    }
  ],
  "surface": {
    "capabilities": [
      {
        "name": "actions.capability.AUDIO_OUTPUT"
      },
      {
        "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
      }
    ]
  },
  "isInSandbox": true,
  "availableSurfaces": [
    {
      "capabilities": [
        {
          "name": "actions.capability.AUDIO_OUTPUT"
        },
        {
          "name": "actions.capability.SCREEN_OUTPUT"
        }
      ]
    }
  ]
}```

**Comment by chrisaspringer** [comment]
It might be this from the Cloudwatch logs actually: 
```
{
    "responseId": "xxxxx",
    "queryResult": {
        "queryText": "GOOGLE_ASSISTANT_WELCOME",
        "parameters": {},
        "allRequiredParamsPresent": true,
        "outputContexts": [
            {
                "name": "projects/xxxx/agent/sessions/xxxx/contexts/google_assistant_welcome"
            },
            {
                "name": "projects/xxxx/agent/sessions/xxxx/contexts/actions_capability_screen_output"
            },
            {
                "name": "projects/xxxx/agent/sessions/xxxx/contexts/actions_capability_audio_output"
            },
            {
                "name": "projects/xxxx/agent/sessions/xxxx/contexts/google_assistant_input_type_keyboard"
            },
            {
                "name": "projects/xxxx/agent/sessions/xxxx/contexts/actions_capability_media_response_audio"
            },
            {
                "name": "projectsxxxx/agent/sessions/xxxx/contexts/actions_capability_web_browser"
            }
        ],
        "intent": {
            "name": "projects/xxxx/agent/intents/xxxx",
            "displayName": "IntroIntent"
        },
        "intentDetectionConfidence": 1,
        "diagnosticInfo": {},
        "languageCode": "en-us"
    },
    "originalDetectIntentRequest": {
        "source": "google",
        "version": "2",
        "payload": {
            "isInSandbox": true,
            "surface": {
                "capabilities": [
                    {
                        "name": "actions.capability.AUDIO_OUTPUT"
                    },
                    {
                        "name": "actions.capability.WEB_BROWSER"
                    },
                    {
                        "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
                    },
                    {
                        "name": "actions.capability.SCREEN_OUTPUT"
                    }
                ]
            },
            "inputs": [
                {
                    "rawInputs": [
                        {
                            "query": "Talk to my test app",
                            "inputType": "KEYBOARD"
                        }
                    ],
                    "intent": "actions.intent.MAIN"
                }
            ],
            "user": {
                "lastSeen": "2018-05-14T21:51:20Z",
                "locale": "en-US",
                "userId": "xxxx"
            },
            "conversation": {
                "conversationId": "xxxx",
                "type": "NEW"
            },
            "availableSurfaces": [
                {
                    "capabilities": [
                        {
                            "name": "actions.capability.AUDIO_OUTPUT"
                        },
                        {
                            "name": "actions.capability.SCREEN_OUTPUT"
                        }
                    ]
                }
            ]
        }
    },
    "session": "xxxxx"
}
```

**Comment by chrisaspringer** [comment]
Using this as the event data I'm testing with locally it appears that session attributes i'm setting aren't accessible in the next line, and that might be another failure area.

**Comment by aswetlow** [comment]
What do you mean with "correct request data."?

I fixed the set/get session attribute issue and pushed it to the master branch. I will publish it to npm tomorrow.

**Comment by chrisaspringer** [comment]
I was using the request data provided by the Actions on Google simulator and not the full request logged by Lambda, so your clarification on what data to use was helpful. 

I think I'll be good to go once the set/get session attribute issue is fixed. However I think that this.nlu.getIntentName() fail point might be an issue.

**Comment by jankoenig** [comment]
Closing this now. Please reopen it if you run into any problems. Thanks
