### ISSUE TITLE
jovo new project creation issue

### ISSUE THREAD

**Issue by GAjayKumar** [jovotech/jovo-framework-nodejs#148]
Hi,

I have an issue while creating new jovo script like below,

  I'm setting everything up

   V Creating new directory /HelloWorld
   | Downloading and extracting template helloworld
     Installing npm dependencies
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 
    at Object._errnoException ()
    at _exceptionWithHostPort ()
    at TCPConnectWrap.afterConnect [as oncomplete] ()

please help me out.

Thanks,
Ajay

**Comment by jankoenig** [comment]
Hey there. Seems like this was a problem with npm.

Can you go into the project directory (`cd HelloWorld`) and try this?

```sh
rm -rf node_modules
npm cache clean
npm install
```

**Comment by GAjayKumar** [comment]
Thank you jankoenig, It helped But after doing it i ran this command Jovo run

it stopped with  

PS C:\Alexa\Hello World\HelloWorld> jovo run
Example server listening on port 3000!

not giving me webhook url.

Regards.

**Comment by jankoenig** [comment]
What happens if you open a new tab and do `jovo run --webhook-only`?

**Comment by GAjayKumar** [comment]
i got webhook url with jovo init command. is it fine

**Comment by jankoenig** [comment]
OK great. Closing this then

**Comment by GAjayKumar** [comment]
can you help

PS C:\Users\user> jovo deploy

   > Deploying Alexa Skill
     x Creating Alexa Skill project for ASK profile default
       -> Unexpected end of JSON input
       Deploying Interaction Model, waiting for build

Unexpected end of JSON input

**Comment by jankoenig** [comment]
Seems like you did some changes to the JSON that make it invalid, try testing it in a tool like this https://jsonlint.com/

**Comment by GAjayKumar** [comment]
Firstly i didn't make any changes to any json file and i have tested the json files in the link you provided, it is showing as valid json.

**Comment by jankoenig** [comment]
Difficult to debug without further information. Have you made any changes to the project or is this a fresh new installation? Did you run "jovo deploy" while being in the root of your project directory?

**Comment by GAjayKumar** [comment]
it's fresh i didn't make any changes. yes i ran "jovo deploy " in the root of your project directory.

**Comment by GAjayKumar** [comment]
First i started with 

1.Npm install -g jovo-cli
2.jovo new helloworld
3.jovo init alexaskill
4.npm install -g ask-cli
5.jovo build
6.jovo deploy

these are tha commands i ran i order at jovo deploy its is showing this error

PS C:\Users\user> jovo deploy

Deploying Alexa Skill
x Creating Alexa Skill project for ASK profile default
-> Unexpected end of JSON input
Deploying Interaction Model, waiting for build

Unexpected end of JSON input

Thanks.

**Comment by jankoenig** [comment]
Did you do "cd helloworld" between steps 2 and 3? It is important to do all project-related things in the project directory

**Comment by GAjayKumar** [comment]
i have done in project directory only .in the project directory it self it is showing the error.

**Comment by jankoenig** [comment]
How does your platforms/alexaSkill/models folder look like? Any files in there? Can you paste the content of the file?

**Comment by GAjayKumar** [comment]
yes one file was present in it  and content pasted below 


{
	"interactionModel": {
		"languageModel": {
			"invocationName": "my test app",
			"types": [],
			"intents": [
				{
					"name": "HelloWorldIntent",
					"samples": [
						"hello",
						"say hello",
						"say hello world"
					]
				},
				{
					"name": "MyNameIsIntent",
					"samples": [
						"{name}",
						"my name is {name}",
						"i am {name}",
						"you can call me {name}"
					],
					"slots": [
						{
							"name": "name",
							"type": "AMAZON.US_FIRST_NAME"
						}
					]
				},
				{
					"name": "AMAZON.CancelIntent",
					"samples": []
				},
				{
					"name": "AMAZON.HelpIntent",
					"samples": []
				},
				{
					"name": "AMAZON.StopIntent",
					"samples": []
				}
			]
		}
	}
}

**Comment by aswetlow** [comment]
What's in your skill.json in /platforms/alexaSkill ?

**Comment by GAjayKumar** [comment]
Hi aswetlow,

skill.json content listed below,


{
	"manifest": {
		"publishingInformation": {
			"locales": {
				"en-US": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"name": "HelloWorld",
					"description": "Sample Full Description"
				}
			},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": "https://webhook.jovo.cloud/2ef0ef34-0468-4730-a755-b1285065917b"
				}
			}
		},
		"manifestVersion": "1.0"
	}
}

Thanks,
Ajay

**Comment by GAjayKumar** [comment]
Any Clue

**Comment by GAjayKumar** [comment]
Can i get this Fixed.

**Comment by jankoenig** [comment]
hi @GAjayKumar, what happens if you create a completely new project? same error?

**Comment by GAjayKumar** [comment]
Yes Jankoenig,

I have Done clearing everything still same issue.

Thanks.

**Comment by jankoenig** [comment]
what node version are you using? did it create a project in the Alexa Developer Console?

**Comment by GAjayKumar** [comment]
iam using NPM -5.6.0 and NODE-v8.11.1. i have created the project in alexa developer console.

**Comment by GAjayKumar** [comment]
i followed this link https://www.jovo.tech/blog/alexa-skill-tutorial-nodejs/#app-configuration

**Comment by jankoenig** [comment]
What happens if you let the Jovo CLI create the project. Maybe this tutorial is better https://youtu.be/i84TXkIenR4

**Comment by GAjayKumar** [comment]
if you can see top 1 st message i tried with Jovo new HelloWorld but i got error for that then i downloaded sample hello world manually.
![image](https://user-images.githubusercontent.com/38782578/40712114-cd4b1080-63f4-11e8-9c25-cc69b48084bf.png)

**Comment by jankoenig** [comment]
Seems like there was a connection error. I'd try it again and see if this changes anything

**Comment by luciilucii** [comment]
Was facing the same issue. I didn't had ask cli installed when I wanted to deploy with jovo. So I added it later, but I was still getting the missing json error, even when I closed the terminal trying jovo build

Then I deleted the project & started the process again. Then it worked fine. 

just fyi

**Comment by rhokstar** [comment]
A problem that AWS doesn't address _clearly_ is the difference between **AWS Console Account** and **Alexa Developer Account**.

Troubleshoot:

1) If you're getting these errors during `ask init`:
```
Switch to 'Login with Amazon' page...
Tokens fetched and recorded in ask-cli config.
Call list-vendors error.
Error code: 401
{
  "message": "You are not authorized to access this operation."
}
```

Or  during `ask status -p [your profile]`

```
[Error]: Cannot resolve profile [your profile]
```

2) If you haven't completed the **Alexa Developer Account** registration, finish this first and then `ask init`. Then execute `jovo deploy`. This should result in `Deployment completed`
