### ISSUE TITLE
Feature: Allow defining Alexa Skill permission settings in app.json

### ISSUE THREAD

**Issue by serg06** [jovotech/jovo-framework-nodejs#168]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Alexa skills have a permission setting in skill.json which it looks like Jovo doesn't support yet:

```
"permissions": [
  {
    "name": "alexa::devices:all:address:full:read"
  }
]
```

(I got it by enabling the permission in UI then doing `jovo get`.)

We should be able to add it to our `app.json` file and, when we build, it should get added to `platforms/alexaSkill/skill.json`.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.2.1
* Operating System: Windows 10

**Comment by aswetlow** [comment]
Hey @serg06! You can put it to the alexaSkill.manifest object:
```
{
	"alexaSkill": {
		"nlu": "alexa",
		"manifest": {
			"permissions": [
				{
					"name": "alexa::devices:all:address:full:read"
				}
			]
		}
	},
	"endpoint": "https://webhook.jovo.cloud/<ID>"
}
```

**Comment by serg06** [comment]
Oh wow, thanks!
