### ISSUE TITLE
How to increase respond timeout for Alexa

### ISSUE THREAD

**Issue by nimmanapallivenu** [jovotech/jovo-framework-nodejs#172]
## I'm submitting a...

- [x] Feature request

## Expected Behavior

 Can anyone help me how i can send asynchronous response after 1 minutes time delay is is possible ?

### Error log
```
If you have an error log, please paste it here.
```
The requested skill took too long to respond
Timeout error: No response after 5000 milliseconds

{ Error: Timeout error: No response after 5000 milliseconds
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12) code: 'ECONNRESET' }

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System:

**Comment by jankoenig** [comment]
Hi @nimmanapallivenu, 

This is the error to investigate: `Error: Can't send more than one response per request.`

Are you sending out two responses with two `tell` or `ask` methods?

**Comment by jankoenig** [comment]
Regarding your edited issue: This doesn't work for 1 minute.

Take a look at Progressive Responses for Alexa: https://www.jovo.tech/docs/amazon-alexa#progressive-responses

**Comment by nimmanapallivenu** [comment]
@jankoenig updated logs details , can you help me how can i increase timeout ? if it is not possible? what was the reason?

**Comment by jankoenig** [comment]
It's not possible. The voice platforms expect a response earlier

**Comment by nimmanapallivenu** [comment]
Thanks @jankoenig Progressive Responses also throwing error when i exceeded response time 5000 milliseconds getting below error log. is there any way to proceed with response time more than 5000 milliseconds ?

Timeout error: No response after 5000 milliseconds

**{ Error: Timeout error: No response after 5000 milliseconds
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12) code: 'ECONNRESET' }
{**

**Comment by nimmanapallivenu** [comment]
@jankoenig How about Push notification when can this feature will be available ?

**Comment by jankoenig** [comment]
It's in beta right now
