### ISSUE TITLE
Doc: Deploy to AWS Lambda

### ISSUE THREAD

**Issue by mastacheata** [jovotech/jovo-framework-nodejs#174]
## I'm submitting a...
- [ ] Bug report
- [ ] Feature request
- [ x ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
The documentation should explain how to configure your Jovo Skill to deploy it to AWS Lambda.

## Current Behavior
The documentation mentions the Jovo Deploy command in the CLI documentation, but no word on how to actually link your AWS account to the Jovo CLI.
No problem, let's look through the other parts of the documentation on how to set up a project for AWS Lambda.
There is a tutorial about how to run a skill on AWS lambda, but that one doesn't use the jovo deploy command at all. Instead it uploads the skill to Lambda by hand.
https://www.jovo.tech/blog/alexa-skill-tutorial-nodejs/#aws-lambda

The Webhook documentation recommends using a local server instead of AWS (https://github.com/jovotech/jovo-framework-nodejs/blob/master/docs/03_app-configuration/02_server/webhook.md#deploy-to-a-server) and then links to the configuration guide for Lambda (https://github.com/jovotech/jovo-framework-nodejs/blob/master/docs/03_app-configuration/02_server/aws-lambda.md)

Neither of these explain how to instruct the jovo-cli tool to upload to AWS.

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.2.1
* Operating System: Win10 x64

**Comment by jankoenig** [comment]
Thanks! You're right. Adding this to the ToDo list for the docs this week

**Comment by jankoenig** [comment]
Finally published this, hope it's helpful: https://www.jovo.tech/docs/kb/deploy-lambda-cli
