### ISSUE TITLE
jovo deploy does nothing

### ISSUE THREAD

**Issue by mastacheata** [jovotech/jovo-framework-nodejs#175]
## I'm submitting a...

- [ x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

jovo deploy -t lambda
should do anything. Either create the zip file for manual deployment or better yet deploy the skill to AWS lambda directly.

## Current Behavior

`λ  jovo deploy -t lambda

   √ Deploying Alexa Skill

  Deployment completed.`

The AWS Lambda dashboard shows that the corresponding function wasn't updated in the last hour (that was when I last updated it by hand).

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.2.1
* Operating System: Win 10 x64 Build 1803

**Comment by jankoenig** [comment]
Thanks! Yes, working on it (and closing it here)
