### ISSUE TITLE
missing certificate url

### ISSUE THREAD

**Issue by JMorell** [jovotech/jovo-framework-nodejs#182]
## I'm submitting a...
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Deploy alexa skill on my webserver.

## Current Behavior
I added `const Webhook = require('jovo-framework').WebhookVerified;` on the index.js and my host return this error: 
> {"status":"failure","reason":"missing certificate url"}

### Error log
`certUrl = req.headers.signaturecertchainurl ` This return **undefined** on alexa-verifier-middleware

## Your Environment
* Jovo Framework version used: 1.2.2
* Operating System: Linux Server

**Comment by anmolagar** [comment]
same issue. Any updates on this?

**Comment by JMorell** [comment]
Not yet.

**Comment by anmolagar** [comment]
So,
require('jovo-framework').Webhook works for dialogflow but not alexa.
Now, i am struggling in running my endpoint on alexa. Btw, i am using heroku for hosting the endpoint and not AWS lamda.

Any help is much appreciated

**Comment by anmolagar** [comment]
@aswetlow @jankoenig 
Issue still persist:
Repro steps:
1. I am using heroku free dyno as mentioned in this doc https://www.jovo.tech/blog/deploy-to-heroku/
2. In alexa skill endpoint section i have selected "My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority"

I am guessing its something related to server certificate settings. Please help

**Comment by anmolagar** [comment]
I just took out the middleware and simply used `Webhook.post` that solved the problem.
btw while setting up endpoint i need to select **the subdomain has the ssl certificates**

**Comment by anmolagar** [comment]
I guess a documentation updation is needed on the jovo website to make it more clear.

**Comment by JMorell** [comment]
Did you get Amazon to accept it by posting the skill? Could you pass the code fragment?

**Comment by aswetlow** [comment]
Hey! I just ran the Functional Test on the Alexa Skills Kit with the following code:  (deployed on Heroku)
```
const {WebhookVerified, Webhook} = require('jovo-framework');
const {app} = require('./app/app.js');

// =================================================================================
// Server Configuration
// =================================================================================

if (app.isWebhook()) {
    const port = process.env.PORT || 3000;
    Webhook.listen(port, () => {
        console.log(`Example server listening on port ${port}!`);
    });
    Webhook.post('/webhook', (req, res) => {
        console.log(req.headers);
        
        app.handleWebhook(req, res);
    });

}
```
I got this result: 
![image](https://user-images.githubusercontent.com/14978292/42997155-fbf0a8de-8c15-11e8-8994-09c437a34edc.png)

After chaniging to the WebhookVerfied, I got zero errors:
```
const {WebhookVerified, Webhook} = require('jovo-framework');
const {app} = require('./app/app.js');

// =================================================================================
// Server Configuration
// =================================================================================

if (app.isWebhook()) {
    const port = process.env.PORT || 3000;
    WebhookVerified.listen(port, () => {
        console.log(`Example server listening on port ${port}!`);
    });
    WebhookVerified.post('/webhook', (req, res) => {
        console.log(req.headers);
        
        app.handleWebhook(req, res);
    });
}
```
![image](https://user-images.githubusercontent.com/14978292/42997233-41859544-8c16-11e8-890f-3bd1b98ad71c.png)


@JMorell 
That should be accepted by Amazon.

**Comment by JMorell** [comment]
@aswetlow yes, It works, thanks!
