### ISSUE TITLE
AMAZON.StopIntent is not triggered

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-framework-nodejs#186]
## I'm submitting a...
- [X ] Bug report

## Expected Behavior
When I build the Jovo HelloWorld Template, I add the AMAZON.StopIntent with this.tell("This text is never read"). 

I say "Alexa, open my test app" 
She replies : Hello World! What's your name?
If I say: "Stop" she should reply "This text is never read" and shut down.

## Current Behavior
When I try to trigger this intent, the skill just shuts down without reading my prompt.
The AMAZON.HelpIntent is working though.

### Error log

code
```
app.setHandler({
    'LAUNCH': function() {
        this.toIntent('HelloWorldIntent');
    },

    'HelloWorldIntent': function() {
        this.ask('Hello World! What\'s your name?', 'Please tell me your name.');
    },

    'MyNameIsIntent': function(name) {
        this.tell('Hey ' + name.value + ', nice to meet you!');
    },

    'AMAZON.HelpIntent': function(name) {
        this.tell('Help is triggered');
    },

    'AMAZON.StopIntent': function(name) {
        this.tell('Stop wont trigger');
    },
});
```
For AMAZON.StopIntent
```
{
	"version": "1.0",
	"response": {
		"shouldEndSession": true
	},
	"sessionAttributes": {}
}
```
For AMAZON.HelpIntent
```
{
	"version": "1.0",
	"response": {
		"shouldEndSession": true,
		"outputSpeech": {
			"type": "SSML",
			"ssml": "<speak>Help is triggered</speak>"
		}
	},
	"sessionAttributes": {}
}
```

## Your Environment
* Jovo Framework version used: 1.3
* Operating System: MacOS

**Comment by jankoenig** [comment]
Hi @QuentinDela, the `AMAZON.StopIntent` is mapped to the `END` handler by default

**Comment by QuentinDela** [comment]
Alright! thanks for the super fast reply.
