### ISSUE TITLE
File DB and Dynamo are not interchangeable

### ISSUE THREAD

**Issue by tony-gutierrez** [jovotech/jovo-framework-nodejs#189]
It would be good to be able to use file for dev, and dynamo on the server. However fileDB is missing things like "db.saveFullObject"

**Comment by jankoenig** [comment]
Hi @tony-gutierrez,
FileDB (`FilePersistencev2`) and Dynamo are interchangeable. Can you share a specific code example that's throwing an error?

**Comment by tony-gutierrez** [comment]
Will look into v2

**Comment by jankoenig** [comment]
OK. v2 is default, so it should work right off the shelf

**Comment by tony-gutierrez** [comment]
I think we need to make v2 the default here: 
https://github.com/jovotech/jovo-framework-nodejs/blob/d1ad6610cf6e5659fb93392ebe08b0b699cb77e5/index.js#L4

**Comment by aswetlow** [comment]
Fixed it. Thanks @tony-gutierrez
