### ISSUE TITLE
ERR: jovo Build --reverse

### ISSUE THREAD

**Issue by soltrinox** [jovotech/jovo-framework-nodejs#192]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Import and reverse the intents from Google Dialog Flow

## Current Behavior
Fails on reverse from en

### Error log
```
jovo build googleAction --reverse
 
   ❯ Building language model platform model
     ❯ Reversing model files
       ✖ en
         -> Cannot read property 'substr' of undefined
{ TypeError: Cannot read property 'substr' of undefined
    at Function.reverse (/usr/lib/node_modules/jovo-cli/helper/dialogFlowAgent.js:182:60)
```

## Your Environment

* Jovo Framework version used: 1.1.8
* Operating System:  Ubuntu 16.04

**Comment by soltrinox** [comment]
also it is not importing en-US intents from dialogFlow when you run 'jovo get'

**Comment by jankoenig** [comment]
Hey there. Could you share a little more about your setup on Dialogflow? So it seems like you have `en` and `en-US` as locales?  Anything else that's helpful for us to debug?

Also, which version of the Jovo CLI are you using? (`jovo -v`)

**Comment by soltrinox** [comment]
I have noticed, that the CLI does not import the en-US locale intents off of Google..  Is there something missing in the app.json which prevents this?  Is there a specific section of my APP.json i am missing?

''''''
{
	"googleAction": {
		"nlu": {
			"name": "dialogflow",
			"version": 2
		}
	},
	"endpoint": "https://webhook.jovo.cloud/c0f62ef0-4551-4cb8-9ff8-ab2a72b8f2fc",
	"alexaSkill": {
		"nlu": "alexa"
	}
}
''''''

I am using the latest 1.1.8 jovo

**Comment by soltrinox** [comment]
So   there are several thing i have noticed with the Google 'jovo build --reverse' and the 'jovo get googleAction'   the support for multiple locales is not getting the full thing.

**Comment by aswetlow** [comment]
Hey @soltrinox 
Sorry for the long wait. It should be fixed now (jovo cli v1.1.13)

**Comment by soltrinox** [comment]
What should the app.json reflect in order to get all locale  from dialogFlow ?

Mine looks like this : 

`{
  "googleAction": {
    "nlu": {
      "name": "dialogflow",
      "version": 2
    },
    "dialogflow": {
      "projectId": "aichart2-c88a6",
      "keyFile": "aichart2-c88a6-cdf110cf88c5.json"
    }
  },
  "endpoint": "https://webhook.jovo.cloud/c0f62ef0-4551-4cb8-9ff8-ab2a72b8f2fc"
}`

**Comment by soltrinox** [comment]
https://github.com/jovotech/jovo-sample-voice-app-nodejs/issues/5

**Comment by aswetlow** [comment]
Hey @soltrinox 

In my case `jovo get googleAction` downloaded all locales from the project to `/platforms/googleAction/dialogflow`. After `jovo build --reverse` everything is generated to the language specific Jovo Language Model files to `/models`

Have you updated the Jovo CLI to version 1.1.13? You should also do `npm install jovo-framework` in your project folder.
