### ISSUE TITLE
How to run jovo from Docker

### ISSUE THREAD

**Issue by sreedharan-chandra** [jovotech/jovo-framework-nodejs#203]
## I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe: Docker support for Jovo

## Expected Behavior
Jovo run should work while running as docker image file

## Current Behavior
Build Docker image for Jovo Application and trying to run as docker. It fails.
###My Docker File
FROM node:carbon

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "jovo", "run" ]

### Error log
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"jovo\": executable file not found in $PATH": unknown.
```

## Your Environment

* Jovo Framework version used:  "^1.2.1"* 
Operating System: Windows/Linux

**Comment by aswetlow** [comment]
Try
CMD [ "node", "index.js", "--webhook" ] instead of CMD [ "jovo", "run" ]

**Comment by sreedharan-chandra** [comment]
Thanks for the response. But what will be the webhook URL? I am running docker image from Linux host

**Comment by jankoenig** [comment]
Hi @sreedharan-chandra, we will shortly post a guide about hosting a Jovo app with Docker. Stay tuned

**Comment by aswetlow** [comment]
How do I reach your Docker from outside? You can use the same IP + Port 3000

**Comment by sreedharan-chandra** [comment]
@aswetlow @jankoenig ,

Thanks for your response. I'm able to resolve this issue.
**CMD [ "node", "index.js", "--webhook" ]** - solves the issue and to access , use the deployed server IP and Port mentioned specified in the docker file.

In this case, the Docker Run Command will be,

**docker run -d -p 3000:3000 [-e ENV_VAR='value'] DOCKER_IMAGE_NAME**
