### ISSUE TITLE
How to force sign out a user to be able to re login with different account?

### ISSUE THREAD

**Issue by mewben** [jovotech/jovo-framework-nodejs#206]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

`this.googleAction().showAccountLinkingCard();` doesn't show the login ui after my account is linked. 
My question is, how to unlink my account so the login ui appears again?

**Comment by KaanKC** [comment]
Disabling and reenabling the Action should unlink the account. You can disable testing with a button on the top right side of the simulator. It's right next to the mute button.

**Comment by mewben** [comment]
@KaanKC Thanks for this. This is very helpful in development. How about in production? Do we have a facility to logout/unlink a user like when a user says, "Log me out"?

**Comment by KaanKC** [comment]
I don't think so.

**Comment by jankoenig** [comment]
I've done some digging, and it seems like this isn't possible currently. Will implement it as soon as this feature is supported by Google Assistant!
