### ISSUE TITLE
Can we have multiple model json files per locale

### ISSUE THREAD

**Issue by aonamrata** [jovotech/jovo-framework-nodejs#210]
## I'm submitting a...

- [ ] Bug report
- [x ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

We are trying to build couple of intents with custom slots, so want to keep them in separate file rather than one huge json file. Is that possible or any pre-build step that can do that?

### Error log
```
If you have an error log, please paste it here.
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System: windows8

**Comment by aswetlow** [comment]
Not possible yet, but we will put it on our list. Thanks!

**Comment by aonamrata** [comment]
ya, did not find anything in the lib. Lets see i might get around doing it and will send out a pull request. 
wondering if that should be a separate command or just a part of `jovo build`?

**Comment by jankoenig** [comment]
thanks @aonamrata , that would be super interesting. for now, it would probably be the easiest solution to have an npm script do re pre-build stuff. we're thinking about ways to make the CLI more extendable though, potentially hooks into every command
