### ISSUE TITLE
read text before videodirective

### ISSUE THREAD

**Issue by vitaliidanchul** [jovotech/jovo-framework-nodejs#212]
![image](https://user-images.githubusercontent.com/30835825/43597335-7482c466-968a-11e8-8792-188de6f38c42.png)

your framework doesn't support fourth parameter

**Comment by aswetlow** [comment]
Hey @vitaliidanchul 
@MerryOscar added it here https://github.com/jovotech/jovo-framework-nodejs/pull/184

See https://github.com/jovotech/jovo-framework-nodejs/blob/master/lib/platforms/alexaSkill/alexaSkill.js#L842

**Comment by vitaliidanchul** [comment]
ok, didn't see that!) Thank you!
