### ISSUE TITLE
Various Credentials Errors w/ Deployment

### ISSUE THREAD

**Issue by ckhicks** [jovotech/jovo-framework-nodejs#225]
## I'm submitting a...
- [x] Bug report

## Expected Behavior
After a successful `jovo build`, I attempt to run `jovo deploy -p alexaSkill` and expect to see the lambda endpoint updated. My `app.json` has the following:
```
{
  "alexaSkill": {
    "nlu": {
      "name": "alexa"
    },
    "skill_id": <my skill id>,
    "askProfile": "default"
  },
  "googleAction": {
    "nlu": {
      "name": "dialogflow"
    },
    "dialogflow": {
      "projectId": <my project id>,
      "keyFile": <my key file>
    }
  },
  "endpoint": <my lambda endpoint>
}
```

## Current Behavior
Result of above commands:

### Error log
```
Deploying Alexa Skill
     ✖ Updating Alexa Skill project for ASK profile default
       -> askApiUpdateSkill:Resource not found.
```

## Your Environment
* Jovo Framework version used: 1.2.0
* Operating System: Mac 10.13.6
* AWS CLI: aws-cli/1.15.58 Python/2.7.15 Darwin/17.7.0 botocore/1.10.57
* ASK CLI: 1.4.1
* Default AWS user config is in place and has fresh security keys from a global IAM admin user

**Comment by jankoenig** [comment]
Can you try again with "skillId"?

**Comment by ckhicks** [comment]
I tried replacing `skill_id` with either `skillid` or `skillId` in my `app.json` and am getting the same error.

I also see that I'm getting the following for `googleAction` deployments as well:
```
   ❯ Deploying Google Action
     ✔ Creating file /googleAction/dialogflow_agent.zip
       Language model: en-US
       Fulfillment Endpoint: <my lambda endpoint>
     ✔ Uploading and restoring agent for project crucible-radio
     ✔ Training started
     ✖ Uploading to lambda
       -> Missing credentials in config
```

Possibly related?

**Comment by ckhicks** [comment]
Yessir, here it is!
```
{
	"manifest": {
		"publishingInformation": {
			"locales": {
				"en-US": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"name": "alexa-crucible-radio",
					"description": "Sample Full Description"
				}
			},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": <my lambda endpoint>
				}
			}
		},
		"manifestVersion": "1.0"
	}
}
```

**Comment by jankoenig** [comment]
OK. Is your AWS default config linked to the ASK default user? You can see all the ASK users with `ask init`

**Comment by ckhicks** [comment]
It appears to be:
```
Profile              Associated AWS Profile
[default]          "__AWS_CREDENTIALS_IN_ENVIRONMENT_VARIABLE__"
```

**Comment by jankoenig** [comment]
Hm, could you maybe try to create a default AWS profile, not the environment variables? It's explained here: https://www.jovo.tech/guides/deploy-lambda-cli#set-up-credentials-with-ask-cli

**Comment by jankoenig** [comment]
No problem 👍

**Comment by kaaloo** [comment]
I can confirm these issues with setting up ask-cli to use environment variables. :(

**Comment by jankoenig** [comment]
Hi @kaaloo, have you tried setting it up again without the environment variables (https://www.jovo.tech/guides/deploy-lambda-cli#set-up-credentials-with-ask-cli) or is it that you specifically want to use those?

**Comment by kaaloo** [comment]
Yes works fine without env vars but I prefer using tools like envchain for sensitive values in the environment.

**Comment by jankoenig** [comment]
You're correct @kaaloo . Will consider this for `v2` of the CLI (@janober is currently working on it)

**Comment by spham** [comment]
Hi, i have same issue when trying to deploy for alexa model

```
  ❯ Deploying Alexa Skill 
      ✖ Updating Alexa Skill project for ASK profile default
       -> askApiUpdateSkill:Resource not found.
        Deploying Interaction Model, waiting for build
```

**Comment by aswetlow** [comment]
Is it an existing skill in your ASK console, @spham?

If yes:
Make sure the skill with the skill id in /platforms/alexaSkill/.ask/config is accessible by the `default` ASK profile

If no:
Set `skillId` to "" in /platforms/alexaSkill/.ask/config
