### ISSUE TITLE
Best practice dealing with different intents across platforms

### ISSUE THREAD

**Issue by mxmtsk** [jovotech/jovo-framework-nodejs#226]
## I'm submitting a...
Best practice question

---
I'm currently migrating my Alexa-only skill to Jovo. Now that it's so easy to build for two platforms I want to offer my skill on Google too. I just wonder what would be *best practice* to deal with the built in Amazon intents that are not available on Google, as I use them heavily in my skill.

This is what I would do and I would appreciate feedback if this is the way to do it or if there is a better way to deal with this topic. Thanks :)

What I'm doing currently:
```Javascript
app.setHandler({
  // example
  'LAUNCH': function() {
  },
  'AMAZON.YesIntent': function() {
    // Logic goes here
  }
});
```

Now to reuse code I'd split it up like this, after I created a Google Only "YesIntent":

```Javascript
const yesIntent = function() {
  // logic
};

app.setHandler({
  // place the generic intents here
  'LAUNCH': function() {
  }
});
app.setAlexaHandler({
  'AMAZON.YesIntent': yesIntent,
});
app.setGoogleActionHandler({
  'YesIntent': yesIntent,
});
```

**Comment by aswetlow** [comment]
Hey @mxmtsk 

You can use the intent map:

```javascript

const app = new App({
      intentMap: {
             'AMAZON.YesIntent': 'YesIntent',
      }
});


```

**Comment by mxmtsk** [comment]
@aswetlow thank! Didn‘t know about that either but this sounds great!
