### ISSUE TITLE
Unit Testing Session Attributes do not reset for each test

### ISSUE THREAD

**Issue by SweetmanTech** [jovotech/jovo-framework-nodejs#241]
## I'm submitting a...

- [x ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

```rb.intent.setSessionAttribute(key,value)``` should only persist for a single test. When a new test without session attributes is run, the old session attributes should be destroyed.

## Current Behavior

Currently Session Attributes persist through all tests in a ```getPlatformRequestBuilder()``` object

### Error log
N/A

## Your Environment

* Jovo Framework version used: 1.1.8
* Operating System: Linux Ubuntu
* Current Code: The session attributes of the first test (without session attributes) is overridden by the second test (with a session attribute)
 ```
describe('Temperature-Test-' + rb.type(), () => {

    it('checks temperature WITHOUT temperature session attribute', () => {
        return send(rb.intent('RoomTemperatureIntent').setAccessToken( accessToken ))
            .then((res) => {
                const matchedResponse = res.isAsk( temperatureResponse , temperatureReprompt );
                expect(matchedResponse).to.equal(true);
            })
    });

    
    it('checks temperature WITH temperature session attribute', () => {
        return send(rb.intent('RoomTemperatureIntent').setAccessToken( accessToken ).setSessionAttribute('temperature', TEMPERATURE))
            .then((res) => {
                const matchedResponse = res.isAsk( temperatureResponse , temperatureReprompt );
                expect(matchedResponse).to.equal(true);
            })
    });

  });
```

**Comment by aswetlow** [comment]
Hey @SweetmanTech 
This will solve it:  `rb.intent('RoomTemperatureIntent').setSessionNew(true)`

**Comment by SweetmanTech** [comment]
You are Right! We should add that to our documentation here: https://www.jovo.tech/docs/unit-testing
