### ISSUE TITLE
Jovo Webhook won't start after command "jovo run"

### ISSUE THREAD

**Issue by miketeistler** [jovotech/jovo-framework-nodejs#245]
## I'm submitting a...
- [x ] Bug report

Hello, when i want to start my Jovo project with the local jovo webhook, i am getting this message.

1.) "Example server listening on port 3000!"

The following line should be the jovo webhook. But instead i am getting this every 30 seconds.

2.) Sorry, there seems to be an issue with the connection!
     timeout

When i use this command "node index.js --webhook", i am only getting message 1.).
When i use this command "jovo run --webhook-only", i am only getting message 2.).

I have also tried to create a new project with the "helloworld" template, but it's the same.

Then i tried to delete the "app.json" file, create a new one with the "jovo init alexaSkill" command and get this output.

   √ Updating /app.json
     √ Adding alexaSkill as platform
     √ Adding platform specific properties to app.json
     √ Adding jovo-webhook as endpoint
       Endpoint uri: <My Webhook Uri>

  Initialization completed.

The Endpoint didn't get checked.
My app.json file looks like this.

{
	"alexaSkill": {
		"nlu": {
			"name": "alexa"
		}
	},
	"endpoint": <My Webhook Uri>
}

I am using Jovo CLI version 1.2.1. I hope you guys can help me with this.

**Comment by aswetlow** [comment]
Hey @miketeistler 
Are you behind a proxy/firewall?
The endpoint in the app.json is empty?
What's in your %USER%/.jovo/config ?
It should look like this:
```
{
	"webhook": {
		"uuid": "<USER-ID>"
	}
}
```

**Comment by miketeistler** [comment]
@aswetlow thanks for your quick  response.
Yes i am behind a proxy, but i already tried without it.
No my Endpoint is not empty, it looks like this "https://webhook.jovo.cloud/c75c21fa...". Didn't know what happend there.
Can you tell where i can find the %USER%/.jovo/config?

**Comment by aswetlow** [comment]
On Windows it's in C:\Users\<USER>\.jovo\config
On Mac in ~/.jovo/config

**Comment by miketeistler** [comment]
Thanks for your help. I have spoken to the admin and maybe it is an internal problem with our network.
I keep you up to date.

**Comment by miketeistler** [comment]
Good news. It was an internal problem with our firewall.
Didn't think about it because it was never a problem before.
Thanks for pushing me in the right direction.
