### ISSUE TITLE
Not able run the Jovo run,  getting "I'm setting everything up"

### ISSUE THREAD

**Issue by manasamansa** [jovotech/jovo-framework-nodejs#250]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
 I am not able to run any Jovo command . 2 days back I tried Hello world example and it worked fine for me in both Alexa and google platform . But today I tried to create my own project getting " "I'm setting everything up" for all the commands which I run using Jovo. 
Also tried in the Hello world example which I worked successfully previously, In that also getting same message. Stucked here. :-(

### Error log
```

C:\Users\user\Documents\AI\claim\Claims Using JOVO\Claims_Cognitive>jovo run
I'm setting everything up

C:\Users\user\Documents\AI\claim\Claims Using JOVO\Claims_Cognitive>jovo run --port 3000
I'm setting everything up
```

## Your Environment

* Jovo Framework version used: 1.x.x
* Operating System: windows 7

**Comment by aswetlow** [comment]
Hey @manasamansa 
Tha'ts weird. `I'm setting everything up` appears only on `jovo new <project>`.
Which version of the Jovo CLI do you use? `jovo -v`

Can't reproduce it with version 1.2.5

**Comment by manasamansa** [comment]
Its 1.2.5

But I am able to resolve this ,Reinstalled JOVO framework and its components . 

Thank you
