### ISSUE TITLE
Alexa's submission process fails due to missing apiEndpoint on dummy request

### ISSUE THREAD

**Issue by shmatul** [jovotech/jovo-framework-nodejs#260]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

Alexa's submission process runs several basic functionality test when submitting a skill, among other things it checks if the launch intent returns a valid response.
Alexa's submission process requests serve a different kind of object rather than when using regular devices / simulator, and it's missing the **apiEndpoint** property (_jovo.platform.request.context.System.apiEndpoint_ === undefined).

## Current Behavior
When outputting a progressiveResponse or any other **apiEndpoint** dependent functions in the launch intent of a skill it will fail Alaxa's subbmisions automated tests.
jovo-framework/lib/platforms/alexaSkill/alexaSkill.js looks for the  **apiEndpoint** and tries to trim it:
```
 hostname: this.request.getApiEndpoint().substr(8), // remove https:// 
```

## Expected Behavior
Until (or if) will get fixed by Amazon, jovo request should fallback apiEndpoint property to 'https://api.amazonalexa.com'.

### Error log
```
2018-10-07T08:13:35.420Z    e3189c42-ca08-11e8-b0c9-6dc90c997f19    HelloWorldIntent
2018-10-07T08:13:35.421Z    e3189c42-ca08-11e8-b0c9-6dc90c997f19    handleLambda err TypeError: Cannot read property 'substr' of undefined
    at AlexaSkill.progressiveResponse (/var/task/node_modules/jovo-framework/lib/platforms/alexaSkill/alexaSkill.js:1154:52)
```

## Your Environment

* Jovo Framework version used: 1.4.11

**Comment by aswetlow** [comment]
Hey @shmatul 
Good point! Would you like to make a pull request?

**Comment by shmatul** [comment]
@aswetlow sure. I'll try to make one that you'll accept :)

**Comment by jankoenig** [comment]
Thanks @shmatul !
