### ISSUE TITLE
Trouble implementing "Unhandled" on Alexa

### ISSUE THREAD

**Issue by alanwork** [jovotech/jovo-framework-nodejs#270]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [X ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior

Hello, I'm having trouble getting my app to trigger the "Unhandled" intent on Alexa. No matter what I do, it seems to trigger the YesIntent instead. It works fine on Google Home. I found some forums from last year suggesting this was an issue with the Alexa NLP, but the recent built-in AMAZON.FallbackIntent is supposed to correct for it.

I've tried to incorporate the built-in AMAZON.FallbackIntent in a separate Alexa language model, as a part of the existing intents (which I've seen while looking up Jovo example apps), and also through an IntentMap variable in the config. Every time, the app triggers a YesIntent, even on edge cases like "banana" or the like.

I can't seem to find docs that recommend what to do in this scenario and I'm not sure if FallbackIntent is supported at all by Jovo. I can't be the only one with this problem, however, so I would like to hear what the best practice for this is.

## Your Environment
Jovo CLI Version: 1.2.7
Windows 7

**Comment by jankoenig** [comment]
Hi @alanwork. "Unhandled" works as a catch all in the handler, not the NLP. So for example, if you have an incoming request with "YesIntent" and "YesIntent" can't be found in your handler, "Unhandled" is triggered. Take a look here to learn more: https://www.jovo.tech/tutorials/unhandled-intent

Unfortunately, there is no real FallbackIntent on Alexa similar to Google Assistant (where you get the raw text). The  AMAZON.FallbackIntent is just a signal that something was misunderstood, with no content _what_ was understood.

Hm, it's really weird that it always triggers the YesIntent. How does your intentMap look like?

**Comment by jankoenig** [comment]
Hey there. Closing this for now. Let us know if you have any more questions.
