### ISSUE TITLE
Alexa Functional tests failed

### ISSUE THREAD

**Issue by ihr-it-projekt** [jovotech/jovo-framework-nodejs#271]
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
- I start my server with jovo run.
- i configure the https://webhook.jovo.cloud/xxxx -xxxxxx-xx url into endpoint config at alexa develop console 
- run the functional tests and get:

> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an empty signature URL.
> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an empty signature URL. Please make sure that your signature validation is correct. To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response.
> Documentation Help:
> Verifying the signature certificate URL: Click here
> 
> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL.
> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL. Please make sure that your signature validation is correct. To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response.
> Documentation Help:
> Verifying the signature certificate URL: Click here
> 
> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an invalid signature URL specified.
> The skill end-point is not validating the signatures for incoming requests and is accepting requests with an invalid signature URL specified. Please make sure that your signature validation is correct. To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response.
> Documentation Help:
> Verifying the signature certificate URL: Click here
> 
> The skill end-point is not validating the signatures for incoming requests and is accepting requests when no signature URL headers are specified.
> The skill end-point is not validating the signatures for incoming requests and is accepting requests when no signature URL headers are specified. Please make sure that your signature validation is correct. To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response.

I try some diffrend like:

```
if (app.isWebhook()) {
  const port = process.env.PORT || 3000;
  WebhookVerified.listen(port, () => {
    console.log(`Example server listening on port ${port}!`);
  });
  WebhookVerified.post('/webhook', (req, res) => {
    app.handleWebhook(req, res);
  });
}

```

or

```
const {app} = require('./app/app.js');
const express = require('express');
const verifier = require('alexa-verifier-middleware');
const bodyParser = require('body-parser');
const http = require('http');

const Webhook = express();
Webhook.listen = function() {
  try {
    let router = express.Router(); //eslint-disable-line
    Webhook.use(router);
    router.use('/webhook_alexa', verifier);
    router.use('/webhook_alexa', bodyParser.json());
    router.use('/webhook', bodyParser.json());
    let server = http.createServer(this);
    return server.listen.apply(server, arguments); // eslint-disable-line
  } catch (error) {
    if (error.code === 'MODULE_NOT_FOUND') {
      console.log('  Please install module alexa-verifier-middleware');
    } else {
      console.log(error);
    }
  }
};

if (app.isWebhook()) {
  const port = process.env.PORT || 3000;
  Webhook.listen(port, () => {
    console.log(`Example server listening on port ${port}!`);
  });
  Webhook.post('/webhook_alexa', (req, res) => {
    app.handleWebhook(req, res);
  });
  Webhook.post('/webhook', (req, res) => {
    app.handleWebhook(req, res);
  });
}

exports.handler = (event, context, callback) => {
  app.handleLambda(event, context, callback);
};
````

or default 

```
'use strict';

const {WebhookVerified, Webhook} = require('jovo-framework');
const {app} = require('./app/app.js');

// =================================================================================
// Server Configuration
// =================================================================================

if (app.isWebhook()) {
  const port = process.env.PORT || 3000;
  Webhook.listen(port, () => {
    console.log(`Example server listening on port ${port}!`);
  });
  Webhook.post('/webhook', (req, res) => {
    app.handleWebhook(req, res);
  });
}

```

Everytime i got the same issue.

I run on the last jovo-cli version with diffrent node versions (6,8,10) 

I dont find any documentation for this... .

**Comment by jankoenig** [comment]
Hi there. The Jovo Webhook is only meant for prototyping purposes. For use in production, please upload to e.g. AWS Lambda (take a look here: https://www.jovo.tech/docs/server/aws-lambda) or a different server (https://www.jovo.tech/docs/server/webhook#deploy-to-a-server).

**Comment by jankoenig** [comment]
Closing this for now. Let us know if you have any additional questions regarding deployment
