### ISSUE TITLE
Google Assistant: Add suggestion chips support

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-framework-nodejs#3]
Suggestion chips are small "quick reply" buttons that show up on the Google Assistant app after an ask-reponse. You can find more information here: https://developers.google.com/actions/assistant/responses#suggestion-chip

**Comment by aswetlow** [comment]
Implemented in v0.6.0

**Comment by ashandilya** [comment]
Thanks for your contribution. Can you tell me how can I implement that code using webhook?

**Comment by aswetlow** [comment]
`this.googleAction().showSuggestionChips(['Suggestion 1', 'Suggestion 2', 'Suggestion 3']);`

https://www.jovo.tech/docs/google-assistant/visual-output#suggestion-chips

**Comment by ashandilya** [comment]
Thanks, man.
