### ISSUE TITLE
Combine index.js and index_lambda.js

### ISSUE THREAD

**Issue by the-davey** [jovotech/jovo-framework-nodejs#31]
Currently the instructions recommend switching to index_lambda.js to deploy to lambda, but if you've developed locally it can be awkward to see the differences in index.js and index_lambda.js which are pertinent. In reality they are very few, so it would be useful to use an environment variable or local variable to branch the serving logic.

```
var isLocal = false;
// Listen for post requests
if(isLocal){
    webhook.listen(3000, function() {
        console.log('Local development server listening on port 3000.');
    });

    webhook.post('/webhook', function(req, res) {
        app.handleRequest(req, res, handlers);
        app.execute();
    });
} else {
   //Lambda
    exports.handler = function(event, context, callback) {
        app.handleRequest(event, callback, handlers);
        app.execute();
    };
}
```

**Comment by jankoenig** [comment]
Done with #79
