### ISSUE TITLE
Cannot fetch value of capitalized letters

### ISSUE THREAD

**Issue by iag** [jovotech/jovo-framework-nodejs#44]
When a parameter is defined in Dialogflow in all capitals, Jovo does not seem to be able to get the value of that parameter.
If debug logging is enabled, you can see the parameter and the value are passed, but when trying to call the parameter from within the function` Intent': function(VARIABLE)` or when using the getInputs() function e.g. `let inputs = app.getInputs(VARIABLE);`,  VARIABLE returns "undefined"

**Comment by jankoenig** [comment]
Thank you! We're using camelCase for entity names as parameters (e.g. first-name can be accessed by firstName), but didn't take into account all caps variable names. Will think about how to make this more clear in the error handling

**Comment by jankoenig** [comment]
Added a little more info here: https://github.com/jovotech/jovo-framework-nodejs/blob/master/docs/03_app-logic/02_data/README.md#input-as-parameter
