### ISSUE TITLE
Resuming a song

### ISSUE THREAD

**Issue by timmyg** [jovotech/jovo-framework-nodejs#46]
First off - LOVE this framework and what you're doing with it - hoping I can contribute.

I am playing a song with
```js
// play
app
  .alexaSkill()
  .audioPlayer()
  .setOffsetInMilliseconds(0)
  .play(url, alexaToken)
  .tell(speech);
```
which works great, but my app got declined because I need to handle the Pause and Resume amazon intents. Below is how I am pausing:
```js
// pause
app
  .alexaSkill()
  .audioPlayer()
  .stop();
app.tell("paused");
```
Is there a current way to resume? Am looking through audioPlayer.js and not seeing anything. 

Thanks!

**Comment by jankoenig** [comment]
Thank you for the kind words!

Here's how I'm doing it:

* In the `AMAZON.PauseIntent`, I save the offset of the current song to the database, e.g. like so: `app.user().data.offset = audioPlayer.getOffsetInMilliseconds();` 
* In the `AMAZON.ResumeIntent`, I use `setOffsetInMilliseconds(app.user().data.offset)` before calling `play`

Does this help?

**Comment by timmyg** [comment]
Actually - may have figured it out - would I just use the setOffsetInMilliseconds and play it again?

**Comment by jankoenig** [comment]
Yes!

**Comment by timmyg** [comment]
yep this worked for me. thanks 👍
