### ISSUE TITLE
app.t('key') and app.speechBuilder().t('key') returning 'undefined'

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-framework-nodejs#47]
I am using **jovo-framework@0.6.19**

Here is the **app configuration**:

```
const app = require('jovo-framework').Jovo;

exports.handler = function (event, context, callback) {

    let languageResources = require('./languageResources');

    let intentMap = {
        'AMAZON.HelpIntent': 'HelpIntent',
        'AMAZON.StopIntent': 'StopIntent',
        'AMAZON.CancelIntent': 'StopIntent',
        'given-name': 'name'
    };

    app.setConfig({
        requestLogging: true,
        responseLogging: true,
        saveUserOnResponseEnabled: true,
        i18n: {
            resources: languageResources,
            config: { returnObjects: true },
        },
    });

    app.handleRequest(event, callback, handlers);
    app.execute();
};
```

And the **languageResources.json** file:

```
{
    "en-US": {
        "translation": {
            "Test": "the answer",
            "Welcome": [
                {
                    "Message": "Welcome message one.",
                    "Hint": "Welcome message one hint.",
                    "Prompt": "How can I help?",
                    "Reprompt": "Welcome message one reprompt or ask for help for more options. What would you like?"
                }
            ],
            "WelcomeBackMessage": [
                "Welcome back!.",
                "Good to see you again."
            ],
            "WelcomeBackPrompt": [
                "What would you like to do?",
                "How can I help?",
                "What would you like?"
            ],
            "WelcomeBackReprompt": [
                "Welcome back one reprompt. You can ask for help for more options. What would you like?",
                "Welcome back two reprompt. I can help you find an urgent care near you. For more options, say 'Help'. What would you like?"
            ],
            "Hints": [
                "hint 1",
                "hint 2"
            ]
        }
    }
}
```

Here are the various responses that I get when I try to get to the resources:
app.t('Test')
"the answer"

app.t('Welcome')
undefined

app.t('WelcomeBackMessage')
undefined

app.t('WelcomeBackPrompt')
undefined

app.t('WelcomeBackReprompt')
undefined

app.t('Hints')
undefined

app.speechBuilder().t('Test').speech
"the answer"

app.speechBuilder().t('Welcome').speech
"undefined"

app.speechBuilder().t('WelcomeBackMessage').speech
"undefined"

app.speechBuilder().t('WelcomeBackPrompt').speech
"undefined"

app.speechBuilder().t('WelcomeBackReprompt').speech
"undefined"

app.speechBuilder().t('Hints').speech
"undefined"

app.speech.t('Test').speech
"the answer the answer the answer"

app.speech.t('Welcome').speech
"the answer the answer the answer undefined"

app.speech.t('WelcomeBackMessage').speech
"the answer the answer the answer undefined undefined"

app.speech.t('WelcomeBackPrompt').speech
"the answer the answer the answer undefined undefined undefined"

app.speech.t('WelcomeBackReprompt').speech
"the answer the answer the answer undefined undefined undefined undefined"

app.speech.t('Hints').speech
"the answer the answer the answer undefined undefined undefined undefined undefined"

**Comment by jankoenig** [comment]
Hi Mark, can you get rid of the array for "Welcome", like so:

```
{
    "en-US": {
        "translation": {
            "Test": "the answer",
            "Welcome":  {
                    "Message": "Welcome message one.",
                    "Hint": "Welcome message one hint.",
                    "Prompt": "How can I help?",
                    "Reprompt": "Welcome message one reprompt or ask for help for more options. What would you like?"
             },
            "WelcomeBackMessage": [
                "Welcome back!.",
                "Good to see you again."
            ],
            "WelcomeBackPrompt": [
                "What would you like to do?",
                "How can I help?",
                "What would you like?"
            ],
            "WelcomeBackReprompt": [
                "Welcome back one reprompt. You can ask for help for more options. What would you like?",
                "Welcome back two reprompt. I can help you find an urgent care near you. For more options, say 'Help'. What would you like?"
            ],
            "Hints": [
                "hint 1",
                "hint 2"
            ]
        }
    }
}
```

You should then be able to access e.g. the hint with `app.t('Welcome.Hint')`.

For the variety-adding arrays, I would use `addText`:

```
let speech = app.speechBuilder()
    .addText(app.t('WelcomeBackMessage'))
   .addText(app.t('WelcomeBackPrompt'));
```

Does this work?

**Comment by rmtuckerphx** [comment]
.t() should be able to return an object or array of strings or array of objects from the localResources and not assume that it is text and not auto-apply .addText() to it. 

I should be able to handle my own random (or ordered) selection from an array returned from localResources.

**Comment by jankoenig** [comment]
Yes, this is what `app.t` should already do. `speechBuilder.t` is a convenience method that allows to easily add language resources (and variety) to a speechbuilder object

**Comment by rmtuckerphx** [comment]
I am loosing functionality that I had in the Alexa Skills Kit for Node.js. 

For the Welcome message example above, I could work around things if I wanted multiple Welcome messages by creating a 'Welcome0', 'Welcome1', etc,

But there are other cases where I have data in JSON format that doesn't need to come from an API call and it would be nice if they were is the same languageResources file because they will need to be translated.

The current implementation allows me to access nested objects using dot notation:

app.t('Welcome.Message')
"Welcome message one."

But I should also be able to reference the top key and get the entire object but this is what I get:
app.t('Welcome')
undefined

That is the purpose of the i18next config setting for { returnObjects: true }

What it comes down to is that jovo is using the i18next library but breaking some of its functionality:
https://www.i18next.com/objects-and-arrays.html

**Comment by jankoenig** [comment]
Hi @rmtuckerphx, this might be a bug, this is exactly why we allow to use the { returnObjects: true } config. We're investigating

**Comment by jankoenig** [comment]
Updated the docs here: https://github.com/jovotech/jovo-framework-nodejs/blob/master/docs/03_app-logic/03_output/i18n.md#i18next-configuration-options

**Comment by rmtuckerphx** [comment]
That was it. Thank you!
