### ISSUE TITLE
i18next language resources - keys displayed

### ISSUE THREAD

**Issue by Catharsis68** [jovotech/jovo-framework-nodejs#57]
Hey!

I've got a question regarding the i18next language resources `app.t('key')`:

`app.tell(app.t('WELCOME'));` 

`const languageResources = {
    'de-DE': {
        translation: {
            WELCOME: 'Willkommen',            
        },
    },
};`

From Google Action Simulator:
> output: 'Willkommen'

From Dialogflow Debugging 
> output: 'WELCOME'

What's the reason for this behaviour? I would expect that the output is the same.
Thanks for your great work!

Best regards

**Comment by aswetlow** [comment]
Hey @Catharsis68! 

Thanks for reaching out. I couldn't reproduce the issue. Did you activate the German locale in DialogFlow?
![image](https://user-images.githubusercontent.com/14978292/34826731-14d910ee-f6d8-11e7-8ea2-4009bef05158.png)

Best
Alex

**Comment by Catharsis68** [comment]
Thanks for the quick response. 
Language in Dialogflow is set to German.

Google Action Simulator => Speaker mode
<img width="527" alt="screen shot 2018-01-11 at 14 16 30" src="https://user-images.githubusercontent.com/6165055/34827402-58df8f5a-f6da-11e7-9057-a969b4b3a350.png">

Directly from Dialogflow
<img width="493" alt="screen shot 2018-01-11 at 14 16 48" src="https://user-images.githubusercontent.com/6165055/34827426-6e2305cc-f6da-11e7-96d2-a3aae8ca9d9a.png">

**Comment by aswetlow** [comment]
Please post the JSON from the DialogFlow request.

**Comment by Catharsis68** [comment]
This is the Dialogflow Request from Dialogflow Web Demo
```js
  Dialogflow Request {
     id:'b139d61d-a693-41eb-8a76-8b32c469639b',
     timestamp:'2018-01-11T13:38:01.721Z',
     lang:'de',
     result:{
        source:'agent',
        resolvedQuery:'frag noize was ich kochen kann',
        speech:'',
        action:'',
        actionIncomplete:false,
        parameters: {
        },
        contexts:[
           {
              name:'session',
              parameters:{
                 date:'2018-01-11',
                 conversationType:'ACTIVE',
                 'date.original':'heute',
                 conversationSection:'NOIZE',
                 'date-period.original':'',
                 conversationPrevIntent:'noize_global_welcome',
                 STATE:'noize_state',
                 'date-period':[]
              },
              lifespan:9992
           },
        ],
        metadata:{
           intentId:'3e2c93aa-e30b-4daf-a2e4-5ecc0f8a1460',
           webhookUsed:'true',
           webhookForSlotFillingUsed:'false',
           intentName:'noize_welcome'
        },
        fulfillment:{
           speech:'Herzlich Willkommen!',
           messages:[
              {
                 type:0,
                 speech:'Herzlich Willkommen!'
              }
           ]
        },
        score:0.8100000023841858
     },
     status:{
        code:200,
        errorType:'success',
        webhookTimedOut:false
     },
     sessionId:'4b544fc9-6315-77aa-f20c-126af6eab0b2'
  }```

**Comment by aswetlow** [comment]
Thanks! And how does the response from your webhook look like?

**Comment by Catharsis68** [comment]
updated the Dialogflow Request above.

One thing I noticed:
In the Dialogflow Request from the Web Demo / Dialogflow Console the
field `originalRequest` in den Request Object is missing. Maybe that could be the reason that the speechBuilder doesn't work correctly?

**Comment by aswetlow** [comment]
That's weird. Shouldn't be a problem with the speech builder.
Could you add an Englisch locale to your language resources? 
What's the output for app.getLocale() ?

**Comment by Catharsis68** [comment]
Output of `app.getLocale()`

#### Actions on Google Simulator 
output: `de-DE`

#### Dialogflow Web Demo
output: `en-US`

I have already `en-US` in my languageResources.
The result of the speechBuilder within webchat only is still something like that
`<speak>NOIZE_WELCOME_ACTIVE NOIZE_WELCOME_ASK</speak>`

Dialogflow language is set to German only
![screen shot 2018-01-12 at 11 30 53](https://user-images.githubusercontent.com/6165055/34871140-c94378c6-f78c-11e7-901b-126fa83f0f1f.png)

**Comment by aswetlow** [comment]
Which version of the the framework do you use?

**Comment by Catharsis68** [comment]
v6.11.0

**Comment by Catharsis68** [comment]
*update*: found the issue, the problem was the wrong locale send from within Dialogflow Console / Web Demo. 
Dialogflow is setting the language code to `en-US` instead of `de-DE` => added the translation for `en-US` and now it works.

Thanks for your help!
