### ISSUE TITLE
using app instead of this in indexGoogleAssistantCards example code?

### ISSUE THREAD

**Issue by MiKiTxn** [jovotech/jovo-framework-nodejs#58]
Hi, 
in the file 
jovo-framework-nodejs/examples/google_action_specific/indexGoogleAssistantCards.js

in the handler for "ON_ELEMENT_SELECTED" it the 'this' element used, shouldn't that be the 'app' element?

well, I did not execute the code, just noticed from reviewing. 

Thank you!
Best Regards
Michael

**Comment by jankoenig** [comment]
Hi Michael, good catch! We're currently restructuring the code. In the future, for the app logic (inside the handler), we will always use `this`, and `app` only for the configuration. Currently, both works.
