### ISSUE TITLE
Add chatbase as an analytics integration

### ISSUE THREAD

**Issue by tomeyerog** [jovotech/jovo-framework-nodejs#62]

**Comment by jankoenig** [comment]
Thanks @tomeyerog!
[Chatbase](https://chatbase.com/welcome) looks definitely interesting and would make a perfect addition to our [Analytics Layer](https://github.com/jovotech/jovo-framework-nodejs/tree/master/lib/integrations/analytics).

**Comment by jankoenig** [comment]
Done with #96
