### ISSUE TITLE
Error using response variations on ask.

### ISSUE THREAD

**Issue by terloon** [jovotech/jovo-framework-nodejs#71]
I enabled returnObjects: true for language resources and it caused an error. I had to change this:

    static toSSML(text) {
        if (!text) {
            throw Error('Invalid output text: ' + text);
        }
        
        // my changes: check for array and randomly choose one.
        if (_.isArray(text)) {
            text = _.sample(text);
        }

        text = text.replace(/<speak>/g, '').replace(/<\/speak>/g, '');
        text = text.replace(/&/g, 'and');

        text = '<speak>' + text + '</speak>';
        return text;
    }

I just wanted to have variations in my .ask( ... ) after a follow up state call. Am I using the ask() incorrectly for language resources that have an array of text options?

**Comment by jankoenig** [comment]
Hi @terloon, to get a random element from the array, please use the Jovo [SpeechBuilder](https://www.jovo.tech/framework/docs/output/speechbuilder#randomized-output).

Arrays in the `ask` method are used for [multiple reprompts in Google Assistant](https://www.jovo.tech/framework/docs/google-assistant#multiple-reprompts).

**Comment by terloon** [comment]
Gotcha. Thanks!
