### ISSUE TITLE
Remove ListTemplate3

### ISSUE THREAD

**Issue by girafic** [jovotech/jovo-framework-nodejs#72]
There is no support for ListTemplate3 on Amazons Alexa.

**Comment by aswetlow** [comment]
Hey @girafic 

It's not documented but there is a ListTemplate3 for the Echo Show :)

![listtemplate3](https://user-images.githubusercontent.com/14978292/35501901-963e1f92-04db-11e8-84ac-f08dc0881221.gif)

**Comment by girafic** [comment]
ohh cool, funny discussion then on Amazon's forum --> https://forums.developer.amazon.com/questions/95176/listtemplate3.html
