### ISSUE TITLE
Keep getting "'final_response' must be set" when testing Google Assistant

### ISSUE THREAD

**Issue by anselanza** [jovotech/jovo-framework-nodejs#74]
I got through the Hello World tutorial just fine, and thought I'd give the AdventureGame one a try. I'm using Google Assistant only (not Alexa) and have everything set up (at least well enough for the HelloWorld example to work!) but now whenever I try to use the Google Assistant simulator, I just get the response "My test app isn't responding right now. Try again soon."

and error message (under Validation Errors):
```
'final_response' must be set
```

Am I missing something? I have set up my BlueDoorIntent and RedDoorIntent as instructed, have the NodeJS server up and running, ngrok proxy URL put into the Fulfillment section on DialogFlow, set Fulfillment to "use webhook" on each Intent, etc.

**Comment by jankoenig** [comment]
Hi! Could you enable logging in the app configuration and tell me what the logs say? Also, is there any stack trace you could share with us? Thanks!

**Comment by anselanza** [comment]
I'm not sure how to enable logging in the app configuration?

There is nothing going on in the app itself (the NodeJS part). Everything works as expected, including responding when I type in the "Try it now" section of DialogFlow. It's only when in Google Assistant simulator that I get this problem.

**Comment by jankoenig** [comment]
Hmm, yes, I've been running in this issue sometimes, that the Simulator isn't working as expected. It might be, for example, that another Action is still enabled for testing. You could also try to fix it be setting an invocation name for your app by filling out the draft information (it shows an error if you don't fill out all the information, but it should still save the invocation name)

**Comment by anselanza** [comment]
Ahhhh... The invocation naming worked perfectly.

**Comment by jankoenig** [comment]
Perfect!

**Comment by anselanza** [comment]
Thank you!

**Comment by jankoenig** [comment]
No problem! Feel free to join our community, if you have more questions: www.jovo.tech/slack

**Comment by reeju10** [comment]
I'm getting the same error. can you tell me how to set invocation name?
