### ISSUE TITLE
Accessing the request sent to Alexa

### ISSUE THREAD

**Issue by rv-ekramer** [jovotech/jovo-framework-nodejs#85]
Hello,

I'm using Jovo to build a skill for Alexa that tells you what streaming services (e.g Netflix, Hulu) a certain show is on.

I would like to be able to log the request sent to the Alexa API for my logging/debugging purposes.

How can I do this?

This is the request that the Alexa API says was sent one of my queries

```json
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>I'm now going to look up the flash</speak>"
			},
			"shouldEndSession": true
		},
		"sessionAttributes": {}
	}
}
```

**Comment by jankoenig** [comment]
Logging of both the incoming request from Alexa (`requestLogging`) and the response (the request sent back to Alexa, `responseLogging`) should be enabled by default in the sample voice app, see here: https://github.com/jovotech/jovo-sample-voice-app-nodejs/blob/master/app/app.js#L9

```js
const config = {
    logging: true,
};
```

Was it this you're looking for or are you looking for a little more flexibility?

**Comment by aswetlow** [comment]
Just added an onRequest and onResponse listener.

```javascript
app.onRequest((jovo) => {
    console.log(jovo.getRequestObject());
});

app.onResponse((jovo) => {
    console.log(jovo.getResponseObject());
});
```
