### ISSUE TITLE
Cannot GET <id>

### ISSUE THREAD

**Issue by mark-hahn** [jovotech/jovo-framework-nodejs#86]
I installed the sample jovo app using `jovo new`.  After doing `jovo run` and then using the suggested URL, I get a webpage that just says `Cannot GET /366dba2c-c4b0-4b00-b143-76dd5040474a`.  What am I doing wrong?

**Comment by jankoenig** [comment]
The suggested URL isn't used as a website, but rather to paste as an endpoint into the respective developer consoles. Take a look here: https://www.jovo.tech/blog/alexa-skill-tutorial-nodejs/#local-prototyping
