### ISSUE TITLE
can't sign up for slack support

### ISSUE THREAD

**Issue by mark-hahn** [jovotech/jovo-framework-nodejs#87]
I don't know where else to post this.  

I can't use slack.  After filling our the sign-up form I am taken to a page that says "Get invited to our community Slack team exchange ideas with fellow Jovo developers. Sign up below:"  But the only thing below that is an ad to create my own typeform.  What am I doing wrong?

**Comment by jankoenig** [comment]
Hi Mark! This is still a manual process, I just invited you. Thanks

**Comment by mark-hahn** [comment]
Thanks to you also.
