### ISSUE TITLE
error in handleElementSelectRequest function

### ISSUE THREAD

**Issue by ALTR8** [jovotech/jovo-framework-nodejs#91]
if (elementId === BaseApp.UNHANDLED &&
            !this.config.handlers[
                BaseApp.REQUEST_TYPE_ENUM.ON_ELEMENT_SELECTED
                ][BaseApp.UNHANDLED]) {
            throw new Error('Error: ' + REQUEST_TYPE_ENUM.ON_ELEMENT_SELECTED + ' with elementId ' + this.getSelectedElementId() + ' has not been defined in the handler.');
    }

In line 967 of jovo.js, BaseApp. needs to be added before REQUEST_TYPE_ENUM.ON_ELEMENT_SELECTED so as not to throw an error when using list templates! It's working for me now!

**Comment by aswetlow** [comment]
Thank you! Fixed.
