### ISSUE TITLE
Error using newly created DynamoDB tables

### ISSUE THREAD

**Issue by brianbrashear** [jovotech/jovo-framework-nodejs#98]
I'm having the same issue as #36 . I created new tables in DynamoDB to take advantage of encryption-at-rest. The table I'm passing to `setDynamoDb` is encrypted, which shouldn't matter. Immediately after launching my Alexa skill, it throws the exception 'Cannot read property userData of null'.

**Comment by jankoenig** [comment]
Did you give your Lambda role the right permissions? https://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html

**Comment by brianbrashear** [comment]
Yes. The skill / Lambda code has been running fine for about 3 months. We are still in development, so yesterday I deleted the Dynamo tables and re-created them with encryption turned on, since recreation is currently the only way to enable encryption.

**Comment by brianbrashear** [comment]
Sorry. Now it's working. I have no idea what happened. I'm assuming it was something on my end. Very strange. Thanks for the quick response. I'll close the issue now.

**Comment by jankoenig** [comment]
Thanks!

**Comment by jankoenig** [comment]
For more support, feel free to join our Slack community as well: https://www.jovo.tech/slack
